AWSTemplateFormatVersion: 2010-09-09
Resources:
  MySecretA:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: MySecretForAppA
      Description: "This secret has a dynamically generated secret password."
      GenerateSecretString:
        PasswordLength: 16
        ExcludePunctuation: true
